Repository CMSgov/qpp-measures-data, pull requests merged in 2024-06, with the labels that each got.

#796 QPPSE-2132: 2nd Dry Run for PY23 Performance Benchmarks in Prod - 5/6
  benchmarks/2023.json
  benchmarks/2023/benchmark-exclusion-reasons.json
  benchmarks/2023/benchmarks-schema.yaml
  scripts/benchmarks/csv-json-converter.ts
  scripts/benchmarks/merge-benchmark-files.ts
  staging/2023/benchmarks/json/mock-cost-benchmarks.json
  staging/2023/benchmarks/json/performance-benchmarks.json
  test/benchmarks/merge-input-files/performance-benchmarks.json
  test/benchmarks/test-benchmarks-merged.json
Labels: version:minor, notes:benchmark-update, PY2023 performance period benchmarks

#803 QPPA-8977: add misc tests
  package-lock.json
  scripts/measures/archive/validate-measures-past-existence.js
  scripts/measures/build-2018-measures
  scripts/mvp/parse-mvp-data
  scripts/mvp/parse-mvp-data-script.spec.ts
  scripts/mvp/parse-mvp-data-script.ts
  scripts/mvp/parse-mvp-data.ts
  test/mvps/measures-data-test.json
  test/mvps/mvp-raw-test-bad-id.json
  test/mvps/mvp-raw-test.json
  test/mvps/mvp-test.json
Labels: notes:chore, version:minor

#804 QPPA-8978: Add unit tests for index.js
  index.js
  index.spec.ts
  package.json
Labels: notes:chore, version:minor

#805 QPPA-8979: Complete mocha-to-Jest migration
  .eslintrc
  .github/workflows/pr-feature.yml
  CONTRIBUTING.md
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/benchmarks/benchmarks.types.ts
  scripts/benchmarks/update-cost-national-averages.spec.ts
  scripts/benchmarks/util.ts
  scripts/benchmarks/validation.business.spec.ts
  scripts/benchmarks/validation.business.ts
  scripts/clinical-clusters/create-clinical-cluster-csv.ts
  scripts/measures/2022/ingest-strata.spec.ts
  scripts/measures/2022/ingest-strata.ts
  scripts/measures/2022/update-measures-util.spec.ts
  scripts/measures/2022/update-measures.spec.ts
  scripts/measures/2022/update-measures.ts
  scripts/measures/2023/ingest-strata.spec.ts
  scripts/measures/2023/ingest-strata.ts
  scripts/measures/2023/update-measures.spec.ts
  scripts/measures/2024/get-stratifications.js
  scripts/measures/2024/ingest-strata.spec.ts
  scripts/measures/2024/ingest-strata.ts
  scripts/measures/2024/update-measures.spec.ts
  scripts/measures/extract-util.js
  scripts/measures/initialize-measures
  scripts/measures/json-to-csv.ts
  scripts/measures/lib/csv-json-converter.spec.ts
  scripts/measures/lib/csv-json-converter.ts
  scripts/measures/lib/measures-lib.ts
  scripts/mvp/2023/update-mvp.ts
  scripts/mvp/2024/update-mvp.ts
  scripts/mvp/csv-json-converter.ts
  scripts/mvp/parse-mvp-data-script.spec.ts
  test/clinical-clusters/clinical-clusters-spec.js
  test/measures/2022/qcdr-strata.csv
  test/measures/examples/quality/019.json
  test/measures/examples/quality/052.json
  test/measures/examples/quality/141.json
  test/measures/examples/quality/204.json
  test/measures/examples/quality/254.json
  test/measures/measures-schema-spec.js
  test/scripts/benchmarks/fixtures/test-benchmarks.csv
  test/scripts/benchmarks/format-benchmark-record-spec.js
  test/scripts/benchmarks/parse-benchmark-data-spec.js
  test/util/benchmarks/is-inverse-benchmark-record-spec.js
Labels: notes:enhancement, version:minor

#806 QPPSE-2419 : 06/13 run of QPPA script for 2023 performanceBenchmarks
  benchmarks/2023.json
  staging/2023/benchmarks/json/performance-benchmarks.json
Labels: version:minor, notes:benchmark-update

#807 QPPA-0000: fix for fx-extra package
  package-lock.json
  package.json
Labels: notes:bug-fix, version:patch

#808 [Snyk] Upgrade yaml from 2.4.2 to 2.4.3
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch
