Repository CMSgov/qpp-measures-data, pull requests merged in 2024-08, with the labels that each got.

#822 QPPA-0000: add npm ignore file
  .npmignore
Labels: notes:bug-fix, version:patch

#823 QPPA-9221: update mvps py2025
  measures/2025/measures-data.json
  mvp/2025/mvp-enriched.json
  mvp/2025/mvp-raw.json
  mvp/2025/mvp.csv
  mvp/2025/mvp.json
  scripts/mvp/csv-json-converter.ts
Labels: version:minor, notes:mvp-update

#824 [Snyk] Upgrade yaml from 2.4.5 to 2.5.0
  package-lock.json
  package.json
Labels: notes:chore, version:patch

#827 QPPA-9423: Adds strong typing to index.ts
  index.spec.ts
  index.ts
  scripts/mvp/2023/update-mvp.ts
  scripts/mvp/2024/update-mvp.ts
  scripts/mvp/2025/update-mvp.ts
  util/interfaces/benchmarks.ts
  util/interfaces/index.ts
  util/interfaces/mvp.ts
  util/interfaces/program-names.ts
Labels: notes:feature, version:patch

#829 QPPA-9423: fix benchmark type
  util/interfaces/benchmarks.ts
Labels: notes:chore, version:patch
