Repository CMSgov/qpp-measures-data, pull requests merged in 2024-04, with the labels that each got.

#783 QPPA-8917: Creates new automated release process
  .github/release-drafer.yml
  .github/release-draft.yml
  .github/workflows/draft-release.yml
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
Labels: feature, minor-update

#784 QPPA-8917: Update publish step for package json files
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/publish.yml
Labels: notes:chore, version:minor

#785 QPPA-8917: cleans up formatting of draft release
  .github/release-drafter.yml
Labels: notes:chore, version:patch

#786 QPPA-8988: Add Benchmarks Cost National Averages
  CONTRIBUTING.md
  README.md
  __mocks__/fs-extra.ts
  benchmarks/2023/cost-national-averages-schema.yaml
  benchmarks/2023/cost-national-averages.json
  benchmarks/2024/cost-national-averages-schema.yaml
  index.js
  package-lock.json
  package.json
  scripts/benchmarks/benchmarks.types.ts
  scripts/benchmarks/build-benchmarks
  scripts/benchmarks/csv-json-converter.ts
  scripts/benchmarks/update-cost-national-averages.spec.ts
  scripts/benchmarks/update-cost-national-averages.ts
  scripts/benchmarks/util.ts
  scripts/benchmarks/validation.business.spec.ts
  scripts/benchmarks/validation.business.ts
  scripts/constants.ts
  scripts/measures/2022/update-measures-util.spec.ts
  scripts/measures/2022/update-measures-util.ts
  scripts/measures/2022/update-measures.spec.ts
  scripts/measures/2022/update-measures.ts
  scripts/measures/2023/update-measures.spec.ts
  scripts/measures/2023/update-measures.ts
  scripts/measures/2024/update-measures.spec.ts
  scripts/measures/2024/update-measures.ts
  scripts/measures/lib/measures-lib.spec.ts
  scripts/measures/lib/measures-lib.ts
  scripts/validate-data.js
  test/benchmarks/bad-measureid-cost-national-averages.csv
  test/benchmarks/cost-national-averages.csv
  util/benchmarks/2023/cost-national-averages.csv
Labels: notes:feature, version:minor

#790 QPPA-9007: Update Github Action for minor fixes and improvements
  .github/workflows/publish.yml
Labels: notes:bug-fix, version:patch

#792 QPPA-9006 resolve npm publish issue
  .github/workflows/publish.yml
Labels: notes:bug-fix, version:patch

#787 [Snyk] Upgrade yaml from 2.4.0 to 2.4.1
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch
