Repository CMSgov/qpp-measures-data, pull requests merged in 2025-02, with the labels that each got.

#898 [Snyk] Upgrade yaml from 2.6.1 to 2.7.0
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#902 [Snyk] Upgrade @types/lodash from 4.17.13 to 4.17.14
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#903 [Snyk] Upgrade papaparse from 5.4.1 to 5.5.0
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#905 [Snyk] Upgrade fs-extra from 11.2.0 to 11.3.0
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#906 QPPC-0000: Diagnosis Exclusion
  claims-related/data/qpp-single-source-2024.json
  claims-related/single_source/format_json.py
  claims-related/single_source/parser.py
  claims-related/tests/test_parse_single_source/test_format_json.py
  measures/2024/measures-data.json
Labels: Ready for Review, version:minor, notes:measure-update

#908 [Snyk] Upgrade papaparse from 5.5.0 to 5.5.2
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#909 [Snyk] Upgrade @types/lodash from 4.17.14 to 4.17.15
  package-lock.json
  package.json
Labels: notes:dependencies, version:patch

#910 QPPA-9729: Remove overallAlgorithm from cost measures
  measures/2025/measures-data.json
  measures/2025/measures-schema.yaml
  mvp/2025/mvp-enriched.json
  scripts/benchmarks/benchmarks.types.ts
  scripts/constants.ts
  scripts/measures/lib/validate-change-requests.ts
  util/interfaces/measure.ts
Labels: version:minor, notes:measure-update
